cgroup: Fix compile error under GCC 8
While testing compilation under Debian 10 with GCC 8, the build failed
due to an error somehow previously unnoticed using GCC 4/9/10.

Fixes the following error during build time:

  kernel/cgroup.c: In function ‘save_set_exclusive_task’:
  kernel/cgroup.c:2757:39: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
       strncpy(tmp->comm, p->comm, sizeof(p->comm));
                                         ^

See also: a6eee6fb83391eec0e5cb220dd999696136559d9
Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>