misc: mediatek: connectivity: wmt_step: Fix compile error on recent GCC
As the driver was being compiled with Werror, the compilation died here.

Instead of checking the whole string (like attempted), we can simply
check if the first character is '\0' as that'll always be the case for
empty non-null strings.

Fixes the following error during compilation:

  drivers/misc/mediatek/connectivity/common/common_main/linux/wmt_step.c: In function 'wmt_step_parse_act_id':
  drivers/misc/mediatek/connectivity/common/common_main/linux/wmt_step.c:451:25: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
    451 |  if (str == NULL || str == '\0')
        |                         ^~
  drivers/misc/mediatek/connectivity/common/common_main/linux/wmt_step.c:451:21: note: did you mean to dereference the pointer?
    451 |  if (str == NULL || str == '\0')
        |                     ^

Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>