power: mediatek: cw2015_fuel_gauge: Fix compile error under recent GCC
As the driver was being compiled with Werror, the compilation died here.

I swear, soon I'm going to run every single one of these crappy drivers
through clang-format (as well as dos2unix as some of them, like this
one, seem to be written under Windows and use CRLR line endings) just
because of all these issues the absolute trash formatting is causing...

Fixes the following error during compilation:

  drivers/power/mediatek/battery/cw2015_fuel_gauge_v3.4.c: In function 'cw_init':
  drivers/power/mediatek/battery/cw2015_fuel_gauge_v3.4.c:289:10: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
    289 |          if (ret < 0)
        |          ^~
  drivers/power/mediatek/battery/cw2015_fuel_gauge_v3.4.c:292:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
    292 |    printk(KERN_ERR"%X\n", reg_val);
        |    ^~~~~~

Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>