(pmOS) "Fix" building under pmbootstrap and aarch64-alpine-linux-musl-ld
The following build errors occur if USB_CONFIGFS_UEVENT is enabled:

    LD [M]  drivers/usb/gadget/libcomposite.o
  aarch64-alpine-linux-musl-ld: drivers/usb/gadget/meta.o: in function `meta_usb_init':
  .../drivers/usb/gadget/meta.c:1312: multiple definition of `init_module'; drivers/usb/gadget/configfs.o:.../drivers/usb/gadget/configfs.c:2031: first defined here
  aarch64-alpine-linux-musl-ld: drivers/usb/gadget/meta.o: in function `cleanup':
  .../drivers/usb/gadget/meta.c:1374: multiple definition of `cleanup_module'; drivers/usb/gadget/configfs.o:.../drivers/usb/gadget/configfs.c:2051: first defined here
  make[4]: *** [../scripts/Makefile.build:472: drivers/usb/gadget/libcomposite.o] Error 1

This will need to be fixed later, but this shall do for initial
development.