usb: gadget: configfs: Fix compilation since v4.4.201 merge
Upstream isn't aware of CONFIG_USB_CONFIGFS_UEVENT -> these functions
are always used; here however both configfs_composite_setup() and
configfs_composite_disconnect() are normally replaced by android_setup()
and android_disconnect().

Fix the issue by only defining the methods when they're actually needed
(when CONFIG_USB_CONFIGFS_UEVENT=n).

Fixes the following errors during build time:

  drivers/usb/gadget/configfs.c:1579:12: error: 'configfs_composite_setup' defined but not used [-Werror=unused-function]
   static int configfs_composite_setup(struct usb_gadget *gadget,
              ^
  drivers/usb/gadget/configfs.c:1604:13: error: 'configfs_composite_disconnect' defined but not used [-Werror=unused-function]
   static void configfs_composite_disconnect(struct usb_gadget *gadget)
               ^

Fixes: f37e434014bbf93864dc85fb318b96226cc4b49b
Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>