misc: mediatek: Adapt drivers to v4.4.168 mm/gup kernel API changes
Adapt MTK drivers to the mm/gup kernel API changes introduced as a part
of v4.4.168 and the commit e96d40bccb37248d109f5518b98626a097cddd5f.

Fixes the following errors during build time:

  drivers/misc/mediatek/m4u/2.0/m4u.c: In function 'm4u_fill_sgtable_user':
  drivers/misc/mediatek/m4u/2.0/m4u.c:409:37: error: passing argument 7 of 'get_user_pages' from incompatible pointer type [-Werror]
        (vma->vm_flags & VM_WRITE), 0, &pages, NULL);
                                       ^
  In file included from include/linux/pid_namespace.h:6:0,
                   from include/linux/ptrace.h:8,
                   from arch/arm64/include/asm/kgdb.h:25,
                   from include/linux/kgdb.h:20,
                   from include/linux/fb.h:4,
                   from drivers/misc/mediatek/m4u/2.0/m4u.c:25:
  include/linux/mm.h:1253:6: note: expected 'struct vm_area_struct **' but argument is of type 'struct page **'
   long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
        ^
  drivers/misc/mediatek/m4u/2.0/m4u.c:408:11: error: too many arguments to function 'get_user_pages'
       ret = get_user_pages(current, current->mm, va_tmp, 1,
             ^
  In file included from include/linux/pid_namespace.h:6:0,
                   from include/linux/ptrace.h:8,
                   from arch/arm64/include/asm/kgdb.h:25,
                   from include/linux/kgdb.h:20,
                   from include/linux/fb.h:4,
                   from drivers/misc/mediatek/m4u/2.0/m4u.c:25:
  include/linux/mm.h:1253:6: note: declared here
   long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
        ^

  drivers/misc/mediatek/gpu/gpu_mali/mali_bifrost/mali-r14p0/drivers/gpu/arm/midgard/mali_kbase_mem.c: In function 'kbase_jd_user_buf_map':
  drivers/misc/mediatek/gpu/gpu_mali/mali_bifrost/mali-r14p0/drivers/gpu/arm/midgard/mali_kbase_mem.c:3259:7: error: passing argument 7 of 'get_user_pages' from incompatible pointer type [-Werror]
      0, pages, NULL);
         ^
  In file included from include/linux/scatterlist.h:7:0,
                   from include/linux/dma-buf.h:29,
                   from drivers/misc/mediatek/gpu/gpu_mali/mali_bifrost/mali-r14p0/drivers/gpu/arm/midgard/mali_kbase_mem.c:30:
  include/linux/mm.h:1253:6: note: expected 'struct vm_area_struct **' but argument is of type 'struct page **'
   long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
        ^
  drivers/misc/mediatek/gpu/gpu_mali/mali_bifrost/mali-r14p0/drivers/gpu/arm/midgard/mali_kbase_mem.c:3255:17: error: too many arguments to function 'get_user_pages'
    pinned_pages = get_user_pages(NULL, mm,
                   ^
  In file included from include/linux/scatterlist.h:7:0,
                   from include/linux/dma-buf.h:29,
                   from drivers/misc/mediatek/gpu/gpu_mali/mali_bifrost/mali-r14p0/drivers/gpu/arm/midgard/mali_kbase_mem.c:30:
  include/linux/mm.h:1253:6: note: declared here
   long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
        ^

Additionally I fixed a lot of other MTK drivers that may or may not be
used later in this tree.

Fixes: e96d40bccb37248d109f5518b98626a097cddd5f
Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>