Revert "usb: gadget: rndis: free response queue during REMOTE_NDIS_RESET_MSG"
This was clearly already in the driver, not sure how this one applied
without me noticing.

Fixes the following errors during build time:

  drivers/usb/gadget/function/rndis.c: In function 'rndis_reset_response':
  drivers/usb/gadget/function/rndis.c:932:6: error: redeclaration of 'length' with no linkage
    u32 length;
        ^
  drivers/usb/gadget/function/rndis.c:926:6: note: previous declaration of 'length' was here
    u32 length;
        ^
  drivers/usb/gadget/function/rndis.c:932:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
    u32 length;
    ^
  drivers/usb/gadget/function/rndis.c:933:6: error: redeclaration of 'xbuf' with no linkage
    u8 *xbuf;
        ^
  drivers/usb/gadget/function/rndis.c:925:6: note: previous declaration of 'xbuf' was here
    u8 *xbuf;
        ^

This reverts commit 6ba88476ef444dad6383be59d59ea57983baf252.