mm: Adapt custom methods to v4.4.168 mm/gup kernel API changes
Adapt these methods to the mm/gup kernel API changes introduced as a
part of v4.4.168 and the commit e96d40bccb37248d109f5518b98626a097cddd5f.

Fixes the following errors during build time:

  mm/gup.c: In function 'get_user_pages_durable':
  mm/gup.c:932:59: error: passing argument 5 of '__get_user_pages_locked' makes pointer from integer without a cast [-Werror]
    return __get_user_pages_locked(tsk, mm, start, nr_pages, write, force,
                                                             ^
  mm/gup.c:687:29: note: expected 'struct page **' but argument is of type 'int'
   static __always_inline long __get_user_pages_locked(struct task_struct *tsk,
                               ^
  mm/gup.c:932:66: error: passing argument 6 of '__get_user_pages_locked' makes pointer from integer without a cast [-Werror]
    return __get_user_pages_locked(tsk, mm, start, nr_pages, write, force,
                                                                    ^
  mm/gup.c:687:29: note: expected 'struct vm_area_struct **' but argument is of type 'int'
   static __always_inline long __get_user_pages_locked(struct task_struct *tsk,
                               ^
  mm/gup.c:933:12: error: passing argument 7 of '__get_user_pages_locked' from incompatible pointer type [-Werror]
              pages, vmas, NULL, false, FOLL_TOUCH | FOLL_DURABLE);
              ^
  mm/gup.c:687:29: note: expected 'int *' but argument is of type 'struct page **'
   static __always_inline long __get_user_pages_locked(struct task_struct *tsk,
                               ^
  In file included from include/uapi/linux/posix_types.h:4:0,
                   from include/uapi/linux/types.h:13,
                   from include/linux/compiler.h:199,
                   from include/linux/linkage.h:4,
                   from include/linux/kernel.h:6,
                   from mm/gup.c:1:
  include/linux/stddef.h:7:14: error: passing argument 9 of '__get_user_pages_locked' makes integer from pointer without a cast [-Werror]
   #define NULL ((void *)0)
                ^
  mm/gup.c:933:25: note: in expansion of macro 'NULL'
              pages, vmas, NULL, false, FOLL_TOUCH | FOLL_DURABLE);
                           ^
  mm/gup.c:687:29: note: expected 'unsigned int' but argument is of type 'void *'
   static __always_inline long __get_user_pages_locked(struct task_struct *tsk,
                               ^
  mm/gup.c:932:9: error: too many arguments to function '__get_user_pages_locked'
    return __get_user_pages_locked(tsk, mm, start, nr_pages, write, force,
           ^
  mm/gup.c:687:29: note: declared here
   static __always_inline long __get_user_pages_locked(struct task_struct *tsk,
                               ^

  fs/proc/task_mmu.c: In function 'seq_print_vma_name':
  fs/proc/task_mmu.c:144:14: error: passing argument 7 of 'get_user_pages' from incompatible pointer type [-Werror]
       1, 0, 0, &page, NULL);
                ^
  In file included from fs/proc/task_mmu.c:1:0:
  include/linux/mm.h:1253:6: note: expected 'struct vm_area_struct **' but argument is of type 'struct page **'
   long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
        ^
  fs/proc/task_mmu.c:143:18: error: too many arguments to function 'get_user_pages'
     pages_pinned = get_user_pages(current, mm, page_start_vaddr,
                    ^
  In file included from fs/proc/task_mmu.c:1:0:
  include/linux/mm.h:1253:6: note: declared here
   long get_user_pages(struct task_struct *tsk, struct mm_struct *mm,
        ^

Fixes: e96d40bccb37248d109f5518b98626a097cddd5f
Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>