net: ipv6: Fix compilation since v4.4.223 merge
Fixes the following error during build time:

  net/ipv6/route.c: In function 'rt6_get_route_info':
  net/ipv6/route.c:2277:6: error: unused variable 'ifindex' [-Werror=unused-variable]
    int ifindex = dev->ifindex;
        ^

Fixes: 0fa840a9f0d7582f944d570c2f2153737a49e792
Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>