mmc: block: mtk: Fix compilation since v4.4.167 merge
Fixes the following error during build time:

  In file included from include/linux/linkage.h:4:0,
                   from include/linux/fs.h:4,
                   from include/linux/debugfs.h:18,
                   from drivers/mmc/card/mtk_mmc_block.c:16:
  In function 'mt_bio_init_ctx',
      inlined from 'mt_bio_queue_alloc' at drivers/mmc/card/mtk_mmc_block.c:158:4:
  include/linux/compiler.h:484:38: error: call to '__compiletime_assert_134' declared with attribute error: BUILD_BUG_ON failed: sizeof(ctx->comm) != TASK_COMM_LEN
    _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                        ^
  include/linux/compiler.h:467:4: note: in definition of macro '__compiletime_assert'
      prefix ## suffix();    \
      ^
  include/linux/compiler.h:484:2: note: in expansion of macro '_compiletime_assert'
    _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
    ^
  include/linux/bug.h:50:37: note: in expansion of macro 'compiletime_assert'
   #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                       ^
  include/linux/bug.h:74:2: note: in expansion of macro 'BUILD_BUG_ON_MSG'
    BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
    ^
  include/linux/sched.h:3072:2: note: in expansion of macro 'BUILD_BUG_ON'
    BUILD_BUG_ON(sizeof(buf) != TASK_COMM_LEN); \
    ^
  drivers/mmc/card/mtk_mmc_block.c:134:2: note: in expansion of macro 'get_task_comm'
    get_task_comm(ctx->comm, thread);
    ^

I used the following as an example while fixing this: https://github.com/smeso/sara/commit/1225233f7a07d2abe6be5b92bfc067ccb029dd20

Fixes: 8810f28fa98da08d496d0cfbdb38716c390ecf8f
Signed-off-by: Jami Kettunen <jami.kettunen@protonmail.com>